name: bitwitsapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_messaging:
  firebase_auth: ^0.16.0
  http: ^0.12.1
  firebase_storage: ^3.1.6
  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  intl: ^0.16.1
  date_format: ^1.0.8
  pin_code_fields: ^3.1.2
  flushbar: ^1.10.4
  flutter_icons: ^1.1.0
  circular_check_box: ^1.0.2
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.17.4
  url_launcher: ^5.4.11
  path_provider: 1.6.1    # For iOS
  snack: ^1.0.4
  json_table:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - svgs/
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/pacifico.ttf
