name: bitwitsapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_messaging:
  firebase_auth: ^0.16.0
  cupertino_icons: ^0.1.3
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.6
  flushbar: ^1.10.4
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.17.4
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - svgs/
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/pacifico.ttf
